name: Actions Tagger

on:
  workflow_dispatch:
  schedule:
  - cron: "0 9 * * 1"

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
      - name: Actions Tagger
        uses: Actions-R-Us/actions-tagger@v2.0.3
