name: Actions Tagger

on:
  workflow_dispatch:
  push:
  release:
    types:
      - released
      - edited
  schedule:
  - cron: "0 9 * * 1"

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
      - name: Keep the versions up-to-date
        uses: Actions-R-Us/actions-tagger@v2
        with:
          publish_latest_tag: true
