name: Sync Upstream-Downstream

on:
  workflow_dispatch:
  schedule:
  - cron: "0 9 * * 1"
  
env:
  WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

jobs:
  get-forked-repos:
    runs-on: ubuntu-latest
    
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
    - name: Get Forked Repos
      id: get-repos
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/orgs/mentordosnerds/repos?type=forks" > repos.json
    - id: set-matrix 
      name: Generate Matrix from File list
      run: |
        echo "::set-output name=matrix::$(jq -r '[.[] | {fileName: .name, filePath: .clone_url, upstreamRepo: .parent.clone_url}]' repos.json)"
        
  sync:
    runs-on: ubuntu-latest
    
    strategy:
      matrix: ${{fromJson(needs.get-forked-repos.outputs.matrix)}}
      
    steps:
    - name: Sync Repo
      uses: dchourasia/sync-upstream-repo@1.01
      with:
        upstream_repo: ${{ matrix.upstreamRepo }}
        downstream_repo: ${{ matrix.filePath }}
        upstream_branch: main
        downstream_branch: main
        token: ${{ env.GITHUB_TOKEN }}
