name: Sync Upstream-Downstream

on:
  workflow_dispatch:
  schedule:
  - cron: "0 9 * * 1"
  
env:
  WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: mentordosnerds/cloudflare-email
      uses: dchourasia/sync-upstream-repo@1.01
      with:
        upstream_repo: "https://github.com/Sh4yy/cloudflare-email.git"
        downstream_repo: "https://github.com/mentordosnerds/cloudflare-email.git"
        upstream_branch: main
        downstream_branch: main
        token: ${{ env.WORKFLOW_TOKEN }}
