name: Sync Upstream-Downstream

on:
  workflow_dispatch:
  schedule:
  - cron: "0 9 * * 1"
  
env:
  WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

jobs:
  get-forked-repos:
    runs-on: ubuntu-latest
    
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
    - name: Get Forked Repos
      id: get-repos
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/orgs/mentordosnerds/repos?type=forks" > repos.json
    - name: Get Parent Repos
      id: get-parents
      run: |
        jq -r '.[] | "\(.full_name) \(.clone_url) \(.url)"' repos.json | while read full_name clone url; do
          parent=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $url | jq -r '.parent.clone_url')
          echo "$full_name $clone $parent" >> matrix.txt
        done
    - id: set-matrix 
      name: Generate Matrix from File list
      run: |
        jq -sR '[split("\n")[:-1][] | {name: .[0], downstreamRepo: .[1], upstreamRepo: .[2]}]' matrix.txt > matrix.json
        echo "matrix=$(jq -c . matrix.json)" >> $GITHUB_OUTPUT
        
  sync:
    runs-on: ubuntu-latest
    
    strategy:
      matrix: ${{fromJson(needs.get-forked-repos.outputs.matrix)}}
      
    steps:
    - name: Sync Repo
      uses: dchourasia/sync-upstream-repo@1.01
      with:
        upstream_repo: ${{ matrix.upstreamRepo }}
        downstream_repo: ${{ matrix.downstreamRepo }}
        upstream_branch: main
        downstream_branch: main
        token: ${{ env.WORKFLOW_TOKEN }}
