name: Sync Upstream-Downstream

on:
  workflow_dispatch:
  schedule:
  - cron: "0 9 * * 1"
  
env:
  WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
    - name: Get Forked Repos
      id: get-repos
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/orgs/mentordosnerds/repos?type=forks" > repos.json
    - name: Get Parent Repos
      id: get-parents
      run: |
        echo '[' > matrix.json
        jq -r '.[] | "\(.full_name) \(.clone_url) \(.url)"' repos.json | while read full_name clone url; do
          repoInfo=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $url)
          parent=$(echo $repoInfo | jq -r '.parent.clone_url')
          default_branch=$(echo $repoInfo | jq -r '.default_branch')
          echo "{\"name\":\"$full_name\", \"downstreamRepo\":\"$clone\", \"upstreamRepo\":\"$parent\", \"defaultBranch\":\"$default_branch\"}," >> matrix.json
        done
        # Remove the trailing comma and close the JSON array
        sed -i '$ s/.$//' matrix.json
        echo ']' >> matrix.json
    - id: set-matrix 
      name: Generate Matrix from File list
      run: |
        echo "matrix=$(cat matrix.json)" >> $GITHUB_ENV
        
  sync:
    needs: set-matrix
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
      
    steps:
    - name: Sync Repo ${{ matrix.name }}
      uses: dchourasia/sync-upstream-repo@1.01
      with:
        upstream_repo: ${{ matrix.upstreamRepo }}
        downstream_repo: ${{ matrix.downstreamRepo }}
        upstream_branch: ${{ matrix.defaultBranch }}
        downstream_branch: ${{ matrix.defaultBranch }}
        token: ${{ env.GITHUB_TOKEN }}
