name: Sync Upstream-Downstream

on:
  workflow_dispatch:
  schedule:
  - cron: "0 9 * * 1"
  
env:
  WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: mentordosnerds/cloudflare-email
      uses: dchourasia/sync-upstream-repo@1.01
      env:
        UPSTREAM_REPO: "https://github.com/Sh4yy/cloudflare-email"
        DOWNSTREAM_REPO: "https://github.com/mentordosnerds/cloudflare-email"
      with:
        upstream_repo: ${{ env.UPSTREAM_REPO }}
        downstream_repo: ${{ env.DOWNSTREAM_REPO }}
        upstream_branch: main
        downstream_branch: main
        token: ${{ env.WORKFLOW_TOKEN }}
